erDiagram
	direction TB
	dim_cryptostock_value {
		INTEGER cryptostock_value_key PK ""  
		DECIMAL high  ""  
		DECIMAL low  ""  
		DECIMAL volume  ""  
		DECIMAL close  ""  
	}

	dim_asset {
		VARCHAR asset_key PK ""  
		ENUM type  ""  
	}

	dim_socioeconomical_indicator {
		VARCHAR socioeconomical_indicator_key PK ""  
		VARCHAR name  ""  
		TEXT description  ""  
	}

	dim_country {
		INTEGER country_key PK ""  
		VARCHAR country_name  ""  
		VARCHAR country_code  ""  
	}

	dim_state {
		INTEGER state_key PK ""  
		VARCHAR state_name  ""  
		VARCHAR state_code  ""  
		INTEGER country_key FK ""  
	}

	dim_metro {
		INTEGER metro_key PK ""  
		VARCHAR metro_name  ""  
		INTEGER state_key FK ""  
	}

	dim_zip {
		INTEGER zip_key PK ""  
		INTEGER city_key FK ""  
	}

	dim_neighborhood {
		INTEGER neighborhood_key PK ""  
		VARCHAR neighborhood_name  ""  
		INTEGER city_key FK ""  
	}

	dim_realstate_indicator {
		VARCHAR realstate_indicator_key PK ""  
		INTEGER region_key FK ""  
		VARCHAR indicator_name  ""  
		TEXT indicator_description  ""  
	}

	dim_value {
		INTEGER value_key PK ""  
		DECIMAL value  ""  
		ENUM unit  ""  
	}

	dim_region {
		INTEGER region_key PK ""  
		VARCHAR region_type  ""  
		INTEGER zip_key FK ""  
		INTEGER neighborhood_key FK ""  
		INTEGER city_key FK ""  
		INTEGER county_key FK ""  
		INTEGER metro_key FK ""  
		INTEGER state_key FK ""  
		INTEGER country_key FK ""  
	}

	dim_time {
		DATE date_key PK ""  
		VARCHAR day_name  ""  
		INTEGER week_number  ""  
		INTEGER month_number  ""  
		VARCHAR month_name  ""  
		INTEGER year  ""  
	}

	fact_value {
		INTEGER value_key FK ""  
		VARCHAR socioeconomical_indicator_key FK ""  
		VARCHAR realstate_indicator_key FK ""  
		VARCHAR cryptostock_value_key FK ""  
		INTEGER country_key PK ""  
		DATE date_key FK ""  
		VARCHAR asset_key FK ""  
	}

	dim_city {
		INTEGER city_key PK ""  
		VARCHAR city_name  ""  
		INTEGER county_key FK ""  
	}

	dim_county {
		INTEGER county_key PK ""  
		VARCHAR county_name  ""  
		INTEGER metro_key FK ""  
	}

	dim_time||--o{fact_value:"year_key"
	dim_value||--o{fact_value:"value_key"
	dim_realstate_indicator||--o{fact_value:"references"
	dim_country||--o{fact_value:"references"
	dim_cryptostock_value||--o{fact_value:"cryptostock_value_key"
	dim_socioeconomical_indicator||--o{fact_value:"references"
	dim_state||--o{dim_metro:"contains"
	dim_metro||--o{dim_county:"contains"
	dim_county||--o{dim_city:"contains"
	dim_city||--o{dim_zip:"contains"
	dim_city||--o{dim_neighborhood:"contains"
	dim_country||--o{dim_state:"references"
	dim_country||--o{dim_region:"references"
	dim_state||--o{dim_region:"references"
	dim_metro||--o{dim_region:"references"
	dim_county||--o{dim_region:"references"
	dim_city||--o{dim_region:"references"
	dim_zip||--o{dim_region:"references"
	dim_neighborhood||--o{dim_region:"references"
	dim_region||--o{dim_realstate_indicator:"references"
	dim_asset||--o{fact_value:"references"